# ~/.config/alacritty/themes/midnight-mint.toml

[colors.primary]
background = "#0f0f17"
foreground = "#c0caf5"

[colors.cursor]
text = "#0f0f17"
cursor = "#9ece6a"

[colors.normal]
black = "#15161e"
red = "#f7768e"
green = "#9ece6a"
yellow = "#e0af68"
blue = "#bb9af7"
magenta = "#bb9af7"
cyan = "#73daca"
white = "#a9b1d6"

[colors.bright]
black = "#414868"
red = "#f7768e"
green = "#b9f27c"
yellow = "#ff9e64"
blue = "#7aa2f7"
magenta = "#bb9af7"
cyan = "#73daca"
white = "#c0caf5"
